apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      labelSelector: >-
        app.kubernetes.io/managed-by=kustomize,
        app.kubernetes.io/component=application
      annotationSelector: kustomize/patch-target=pod-spec
    patch: |
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: media
          hostPath:
            path: /mnt/z2/media/
            type: Directory
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: media
          mountPath: /mnt/z2/media/
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          hostpath.storage.curry/z2: "true"
