apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: StatefulSet
      labelSelector: >-
        app.kubernetes.io/component=postgres,
        app.kubernetes.io/managed-by=kustomize
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/envFrom/-
        value:
          secretRef:
            name: postgres-env
