apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
secretGenerator:
  - name: postgres-env
    options:
      labels:
        app.kubernetes.io/name: _
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/component: postgres

patches:
  - target:
      kind: StatefulSet
      labelSelector: >-
        app.kubernetes.io/component=postgres,
        app.kubernetes.io/managed-by=kustomize
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/envFrom/-
        value:
          secretRef:
            name: postgres-env

replacements:
  - source:
      kind: ConfigMap
      name: kustomize-meta
      fieldPath: data.name
    targets:
      - select:
          kind: Secret
          name: postgres-env
          labelSelector: >-
            app.kubernetes.io/managed-by=kustomize,
            app.kubernetes.io/component=postgres
        fieldPaths:
          - metadata.labels.[app.kubernetes.io/name]
