apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: StatefulSet
      labelSelector: app.kubernetes.io/managed-by=kustomize
    patch: |
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: roobre
