apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - statefulset.yaml
replacements:
  - source:
      kind: ConfigMap
      name: kustomize-meta
      fieldPath: data.name
    targets:
      - select:
          kind: StatefulSet
          labelSelector: app.kubernetes.io/managed-by=kustomize, app.kubernetes.io/component=application
        fieldPaths:
          - metadata.name
          - metadata.labels.[app.kubernetes.io/name]
          - spec.serviceName
          - spec.selector.matchLabels.[app.kubernetes.io/name]
          - spec.template.metadata.labels.[app.kubernetes.io/name]
          - spec.template.spec.containers.[name=_].name
