apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: _
  annotations:
    kustomize/patch-target: pod-spec
  labels:
    app.kubernetes.io/name: _
    app.kubernetes.io/component: application
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: _
  serviceName: _
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: _
    spec:
      containers:
        - name: _
          image: _
          ports: []
          envFrom: []
          volumeMounts: []
          resources: {}
      volumes: []
  volumeClaimTemplates: []
