apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
secretGenerator:
  - name: env
    options:
      labels:
        app.kubernetes.io/name: _
        app.kubernetes.io/managed-by: kustomize-ss-base
patches:
  - target:
      kind: StatefulSet
      name: _
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/envFrom/-
        value:
          secretRef:
            name: env
