apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
secretGenerator:
  - name: env
patches:
  - target:
      kind: StatefulSet
      name: _
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/envFrom/-
        value:
          secretRef:
            name: env
