apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      labelSelector: >-
        app.kubernetes.io/managed-by=kustomize,
        app.kubernetes.io/component=application
      annotationSelector: kustomize/patch-target=pod-spec
    patch: |
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: data
          persistentVolumeClaim:
            claimName: _
          hostPath:
            path: /mnt/znvme/k8s/_
            type: Directory
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          storage.curry/hostpath: znvme
replacements:
  - source:
      kind: ConfigMap
      name: kustomize-meta
      fieldPath: data.name
    targets:
      - select:
          labelSelector: >-
            app.kubernetes.io/managed-by=kustomize,
            app.kubernetes.io/component=application
          annotationSelector: kustomize/patch-target=pod-spec
        fieldPaths:
          - spec.template.spec.volumes.[name=data].persistentVolumeClaim.claimName
      - select:
          kind: PersistentVolumeClaim
          labelSelector: >-
            app.kubernetes.io/managed-by=kustomize,
            app.kubernetes.io/component=application
        fieldPaths:
          - metadata.name
