apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: _
  namespace: _
  annotations:
    kustomize/patch-target: pod-spec
  labels:
    app.kubernetes.io/name: _
    app.kubernetes.io/component: application
    app.kubernetes.io/managed-by: kustomize
spec:
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: _
  namespace: _
  annotations:
    kustomize/patch-target: pod-spec
  labels:
    app.kubernetes.io/name: _
    app.kubernetes.io/component: application
    app.kubernetes.io/managed-by: kustomize
spec:
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: _
    namespace: _
  accessModes:
    - ReadWriteOnce
