apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: StatefulSet
      labelSelector: >-
        app.kubernetes.io/managed-by=kustomize,
        app.kubernetes.io/component=postgres
    patch: |
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: data
          hostPath:
            path: /mnt/znvme/k8s-db/_
            type: Directory
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          storage.curry/hostpath: znvme
replacements:
  - source:
      kind: ConfigMap
      name: kustomize-meta
      fieldPath: data.name
    targets:
      - select:
          kind: StatefulSet
          labelSelector: >-
            app.kubernetes.io/managed-by=kustomize,
            app.kubernetes.io/component=postgres
        fieldPaths:
          - spec.template.spec.volumes.[name=data].hostPath.path
        options:
          delimiter: /
          index: 4
