apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      labelSelector: app.kubernetes.io/managed-by=kustomize, app.kubernetes.io/component=application
      annotationSelector: kustomize/patch-target=pod-spec
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/ports/-
        value:
          containerPort: 0
          name: _
replacements:
  - source:
      kind: ConfigMap
      name: kustomize-meta
      fieldPath: data.port
    targets:
      - select:
          labelSelector: app.kubernetes.io/managed-by=kustomize, app.kubernetes.io/component=application
          annotationSelector: kustomize/patch-target=pod-spec
        fieldPaths:
          - spec.template.spec.containers.0.ports.[name=_].containerPort
  - source:
      kind: ConfigMap
      name: kustomize-meta
      fieldPath: data.name
    targets:
      - select:
          labelSelector: app.kubernetes.io/managed-by=kustomize, app.kubernetes.io/component=application
          annotationSelector: kustomize/patch-target=pod-spec
        fieldPaths:
          - spec.template.spec.containers.0.ports.[name=_].name
