apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: StatefulSet
      labelSelector: app.kubernetes.io/managed-by=kustomize-ss-base
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: data
          mountPath: _
replacements:
  - source:
      kind: ConfigMap
      name: kustomize-meta
      fieldPath: data.mountPath
    targets:
      - select:
          kind: StatefulSet
          labelSelector: app.kubernetes.io/managed-by=kustomize-ss-base
        fieldPaths:
          - spec.template.spec.containers.0.volumeMounts.[name=data].mountPath
