apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - service.yaml
replacements:
  - source:
      kind: ConfigMap
      name: kustomize-meta
      fieldPath: data.name
    targets:
      - select:
          kind: Service
          labelSelector: >-
            app.kubernetes.io/managed-by=kustomize,
            app.kubernetes.io/component=application
        fieldPaths:
          - metadata.name
          - metadata.labels.[app.kubernetes.io/name]
          - spec.selector.[app.kubernetes.io/name]
          - spec.ports.0.name
  - source:
      kind: ConfigMap
      name: kustomize-meta
      fieldPath: data.port
    targets:
      - select:
          kind: Service
          labelSelector: >-
            app.kubernetes.io/managed-by=kustomize,
            app.kubernetes.io/component=application
        fieldPaths:
          - spec.ports.0.port
          - spec.ports.0.targetPort
