apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: Service
      labelSelector: app.kubernetes.io/managed-by=kustomize, app.kubernetes.io/component=application
    patch: |
      - op: replace
        path: /spec/ports/0/port
        value: 80
