apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - backup-schedule.yaml
replacements:
  - source:
      kind: ConfigMap
      name: kustomize-meta
      fieldPath: data.name
    targets:
      - select:
          kind: Schedule
          labelSelector: >-
            app.kubernetes.io/managed-by=kustomize,
            app.kubernetes.io/component=application
        fieldPaths:
          - metadata.name
