---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: _
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: application
spec:
  backend:
    s3:
      endpoint: s3.us-west-002.backblazeb2.com
      bucket: curry-backups
      accessKeyIDSecretRef:
        name: backup-creds
        key: keyID
      secretAccessKeySecretRef:
        name: backup-creds
        key: keySecret
    repoPasswordSecretRef:
      name: backup-creds
      key: password
  backup:
    schedule: '@weekly-random'
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 1
  check:
    schedule: '0 4 * * 1'
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 0
  prune:
    schedule: '0 4 * * 2'
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 0
    retention:
      keepDaily: 3
      keepWeekly: 1
      keepMonthly: 2
