apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
replacements:
  - path: statefulset-volume-repl.yaml
patches:
  - target:
      kind: StatefulSet
      labelSelector: app.kubernetes.io/managed-by=kustomize-ss-base
    patch: |
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: data
          hostPath:
            path: /mnt/zmir/k8s/_
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          storage.curry/hostpath: zmir
