apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      labelSelector: app.kubernetes.io/managed-by=kustomize, app.kubernetes.io/component=application
      annotationSelector: kustomize/patch-target=pod-spec
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/livenessProbe
        value:
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
          httpGet:
            port: _
      - op: add
        path: /spec/template/spec/containers/0/readinessProbe
        value:
          failureThreshold: 1
          httpGet:
            port: _
replacements:
  - source:
      kind: ConfigMap
      name: kustomize-meta
      fieldPath: data.name
    targets:
      - select:
          labelSelector: app.kubernetes.io/managed-by=kustomize, app.kubernetes.io/component=application
          annotationSelector: kustomize/patch-target=pod-spec
        fieldPaths:
          - spec.template.spec.containers.0.livenessProbe.httpGet.port
          - spec.template.spec.containers.0.readinessProbe.httpGet.port
