apiVersion: kustomize.config.k8s.io/v1beta1
kind: Replacement
source:
  kind: ConfigMap
  name: kustomize-meta
  fieldPath: data.name
targets:
  - select:
      kind: StatefulSet
      labelSelector: app.kubernetes.io/managed-by=kustomize-ss-base
    fieldPaths:
      - spec.volumeClaimTemplates.0.metadata.name
