apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
replacements:
  - source:
      kind: ConfigMap
      name: meta
      fieldPath: data.name
    targets:
      - select:
          kind: StatefulSet
          name: _
        fieldPaths:
          - metadata.name
          - metadata.labels.[app.kubernetes.io/name]
          - spec.serviceName
          - spec.selector.matchLabels.[app.kubernetes.io/name]
          - spec.template.metadata.labels.[app.kubernetes.io/name]
          - spec.template.spec.containers.[name=_].name
      - select:
          kind: Service
          name: _
        fieldPaths:
          - metadata.name
          - metadata.labels.[app.kubernetes.io/name]
          - spec.selector.[app.kubernetes.io/name]
          - spec.ports.0.name
      - select:
          kind: Ingress
          name: _
        fieldPaths:
          - metadata.name
          - metadata.labels.[app.kubernetes.io/name]
          - spec.rules.0.http.paths.0.backend.service.name
          - spec.rules.0.http.paths.0.backend.service.port.name
