apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - service.yaml
replacements:
  - path: service-repl.yaml
  - path: statefulset-repl.yaml
patches:
  - patch: |
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: _
      spec:
        template:
          spec:
            containers:
              - name: _
                ports:
                  - containerPort: 0
