apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - service.yaml
replacements:
  - path: service-port-repl.yaml
  - path: service-name-repl.yaml
  - path: statefulset-port-repl.yaml
patches:
  - target:
      kind: StatefulSet
      labelSelector: app.kubernetes.io/managed-by=kustomize-ss-base
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/ports
        value:
          - containerPort: 0
