apiVersion: kustomize.config.k8s.io/v1beta1
kind: Replacement
source:
  kind: ConfigMap
  name: kustomize-meta
  fieldPath: data.port
targets:
  - select:
      kind: StatefulSet
      labelSelector: app.kubernetes.io/managed-by=kustomize-ss-base
    fieldPaths:
      - spec.template.spec.containers.0.ports.0.containerPort
