resources:
  - meta.yaml

components:
  - ../_resources/ingress/internal
  - ../_resources/ingress/external
  - ../_resources/ss-base
  - ../_resources/ss-base/hostpath
  - ../_resources/ss-base/service
  - ../_resources/_names

patches:
  - target:
      kind: Ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: testapp.terabox.moe

images:
  - name: _
    newName: ghcr.io/roobre/testapp:1.2.3
