resources:
  - meta.yaml

images:
  - name: _
    newName: ghcr.io/roobre/testapp:1.2.3

components:
  - ../_resources/ss-base
  - ../_resources/ss-base/service
  - ../_resources/ss-base/hostpath
  - ../_resources/ss-base/pvc
  - ../_resources/ss-base/pvc/nfs
  - ../_resources/ss-base/env-configmap
  - ../_resources/ss-base/env-secret
  - ../_resources/ingress-internal
  - ../_resources/ingress-external

configMapGenerator:
  # Add things to the env-configmap component
  - name: env
    behavior: replace
    literals:
      - TZ=Europe/Madrid

patches:
  # Change ingress hostnames
  - target:
      kind: Ingress
      labelSelector: app.kubernetes.io/managed-by=kustomize-ingress

    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: testapp.terabox.moe
