resources:
  - meta.yaml

images:
  - name: _
    newName: ghcr.io/roobre/testapp:1.2.3

components:
  - ../_resources/ss-base
  - ../_resources/ss-base/service
  - ../_resources/ss-base/hostpath
  - ../_resources/ss-base/env-configmap
  - ../_resources/ingress/internal
  - ../_resources/ingress/external
  - ../_resources/_names

configMapGenerator:
  # Add things to the env-configmap component
  - name: env
    behavior: replace
    literals:
      - TZ=Europe/Madrid
  # Create a custom configmap with config
  - name: config
    files:
      - example.conf

patches:
  # Change ingress hostnames
  - target:
      kind: Ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: testapp.terabox.moe

  # Add custom configMap
  - patch: |
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: _
      spec:
        template:
          spec:
            volumes:
              - name: config
                configMap:
                  name: config
            containers:
              - name: testapp
                volumeMounts:
                  - mountPath: /config/foo.conf
                    name: config
                    subpath: foo.conf
