apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ingress.yaml
replacements:
  - source:
      kind: ConfigMap
      name: kustomize-meta
      fieldPath: data.name
    targets:
      - select:
          kind: Ingress
          labelSelector: >-
            app.kubernetes.io/managed-by=kustomize,
            app.kubernetes.io/component=application,
            app.kubernetes.io/instance=main
        fieldPaths:
          - metadata.name
          - metadata.labels.[app.kubernetes.io/name]
          - spec.rules.0.http.paths.0.backend.service.name
          - spec.rules.0.http.paths.0.backend.service.port.name
