apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
  - name: env
    options:
      labels:
        app.kubernetes.io/name: _
        app.kubernetes.io/managed-by: kustomize-ss-base
patches:
  - target:
      kind: StatefulSet
      labelSelector: app.kubernetes.io/managed-by=kustomize-ss-base
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/envFrom/-
        value:
          configMapRef:
            name: env
replacements:
  - source:
      kind: ConfigMap
      name: kustomize-meta
      fieldPath: data.name
    targets:
      - select:
          kind: ConfigMap
          labelSelector: app.kubernetes.io/managed-by=kustomize-ss-base
        fieldPaths:
          - metadata.labels.[app.kubernetes.io/name]
