apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - statefulset.yaml
  - service.yaml

configMapGenerator:
  - name: postgres-env
    literals:
      - POSTGRES_USER=_
      - POSTGRES_DB=_
    options:
      labels:
        app.kubernetes.io/name: _
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/component: postgres

secretGenerator:
  - name: postgres-env
    options:
      labels:
        app.kubernetes.io/name: _
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/component: postgres

replacements:
  - source:
      kind: ConfigMap
      name: kustomize-meta
      fieldPath: data.name
    targets:
      - select:
          kind: ConfigMap
          name: postgres-env
          labelSelector: app.kubernetes.io/managed-by=kustomize, app.kubernetes.io/component=postgres
        fieldPaths:
          - data.POSTGRES_USER
          - data.POSTGRES_DB
          - metadata.labels.[app.kubernetes.io/name]
      - select:
          kind: Secret
          name: postgres-env
          labelSelector: app.kubernetes.io/managed-by=kustomize, app.kubernetes.io/component=postgres
        fieldPaths:
          - metadata.labels.[app.kubernetes.io/name]
      - select:
          kind: StatefulSet
          labelSelector: app.kubernetes.io/managed-by=kustomize, app.kubernetes.io/component=postgres
        fieldPaths:
          - metadata.name
          - metadata.labels.[app.kubernetes.io/name]
          - spec.selector.matchLabels.[app.kubernetes.io/name]
          - spec.template.metadata.labels.[app.kubernetes.io/name]
        options:
          delimiter: "-"
      - select:
          kind: Service
          labelSelector: app.kubernetes.io/managed-by=kustomize, app.kubernetes.io/component=postgres
        fieldPaths:
          - metadata.labels.[app.kubernetes.io/name]
          - spec.selector.[app.kubernetes.io/name]
