apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: _
    app.kubernetes.io/component: postgres
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    app.kubernetes.io/name: _
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
