apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: _-postgres
  annotations:
    kustomize/patch-target: pod-spec
  labels:
    app.kubernetes.io/name: _
    app.kubernetes.io/component: postgres
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: _
      app.kubernetes.io/component: postgres
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: _
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - name: postgres
              containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-env
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources: {}
          readinessProbe:
            failureThreshold: 1
            periodSeconds: 5
            exec:
              command:
                - pg_isready
                - --timeout=1
      volumes: []
  volumeClaimTemplates: []
